// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package poc_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CheckServiceClient is the client API for CheckService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CheckServiceClient interface {
	HasWork(ctx context.Context, in *CheckWorkRequest, opts ...grpc.CallOption) (*CheckWorkResponse, error)
	DoWork(ctx context.Context, opts ...grpc.CallOption) (CheckService_DoWorkClient, error)
}

type checkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCheckServiceClient(cc grpc.ClientConnInterface) CheckServiceClient {
	return &checkServiceClient{cc}
}

func (c *checkServiceClient) HasWork(ctx context.Context, in *CheckWorkRequest, opts ...grpc.CallOption) (*CheckWorkResponse, error) {
	out := new(CheckWorkResponse)
	err := c.cc.Invoke(ctx, "/poc.CheckService/HasWork", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkServiceClient) DoWork(ctx context.Context, opts ...grpc.CallOption) (CheckService_DoWorkClient, error) {
	stream, err := c.cc.NewStream(ctx, &CheckService_ServiceDesc.Streams[0], "/poc.CheckService/DoWork", opts...)
	if err != nil {
		return nil, err
	}
	x := &checkServiceDoWorkClient{stream}
	return x, nil
}

type CheckService_DoWorkClient interface {
	Send(*DoWorkRequest) error
	CloseAndRecv() (*DoWorkResponse, error)
	grpc.ClientStream
}

type checkServiceDoWorkClient struct {
	grpc.ClientStream
}

func (x *checkServiceDoWorkClient) Send(m *DoWorkRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *checkServiceDoWorkClient) CloseAndRecv() (*DoWorkResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(DoWorkResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CheckServiceServer is the server API for CheckService service.
// All implementations must embed UnimplementedCheckServiceServer
// for forward compatibility
type CheckServiceServer interface {
	HasWork(context.Context, *CheckWorkRequest) (*CheckWorkResponse, error)
	DoWork(CheckService_DoWorkServer) error
	mustEmbedUnimplementedCheckServiceServer()
}

// UnimplementedCheckServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCheckServiceServer struct {
}

func (UnimplementedCheckServiceServer) HasWork(context.Context, *CheckWorkRequest) (*CheckWorkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HasWork not implemented")
}
func (UnimplementedCheckServiceServer) DoWork(CheckService_DoWorkServer) error {
	return status.Errorf(codes.Unimplemented, "method DoWork not implemented")
}
func (UnimplementedCheckServiceServer) mustEmbedUnimplementedCheckServiceServer() {}

// UnsafeCheckServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CheckServiceServer will
// result in compilation errors.
type UnsafeCheckServiceServer interface {
	mustEmbedUnimplementedCheckServiceServer()
}

func RegisterCheckServiceServer(s grpc.ServiceRegistrar, srv CheckServiceServer) {
	s.RegisterService(&CheckService_ServiceDesc, srv)
}

func _CheckService_HasWork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckWorkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckServiceServer).HasWork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poc.CheckService/HasWork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckServiceServer).HasWork(ctx, req.(*CheckWorkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckService_DoWork_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CheckServiceServer).DoWork(&checkServiceDoWorkServer{stream})
}

type CheckService_DoWorkServer interface {
	SendAndClose(*DoWorkResponse) error
	Recv() (*DoWorkRequest, error)
	grpc.ServerStream
}

type checkServiceDoWorkServer struct {
	grpc.ServerStream
}

func (x *checkServiceDoWorkServer) SendAndClose(m *DoWorkResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *checkServiceDoWorkServer) Recv() (*DoWorkRequest, error) {
	m := new(DoWorkRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CheckService_ServiceDesc is the grpc.ServiceDesc for CheckService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CheckService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "poc.CheckService",
	HandlerType: (*CheckServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HasWork",
			Handler:    _CheckService_HasWork_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DoWork",
			Handler:       _CheckService_DoWork_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "poc.proto",
}
